name: NestJS CI Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-node_modules-

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build
